// <auto-generated />
using System;
using Avtobus1.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avtobus1.DAL.Migrations
{
    [DbContext(typeof(Avtobus1DbContext))]
    [Migration("20250211221306_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Avtobus1.DAL.Entities.Url", b =>
                {
                    b.Property<string>("ShortUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Сlicks")
                        .HasColumnType("int unsigned");

                    b.HasKey("ShortUrl");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
